### PR TITLE
Keycloak Operator 13.0.0 Operatorhub sync

### PR DESCRIPTION
**Pull request by vmuzikar**
This is just a sync commit. Please merge it after this 2 PRs get in:
* https://github.com/operator-framework/community-operators/pull/3767
* https://github.com/operator-framework/community-operators/pull/3766

### CODE REVIEW

**Comment by vmuzikar** [comment]
@slaskawi I did not. :( Do we expect we have inconsistencies between code and CRDs?

**Comment by vmuzikar** [comment]
@slaskawi Luckily, there are no changes after running `make code/gen`.

**Comment by slaskawi** [comment]
@vmuzikar In general - no but sometimes it happens that some changes go under the radar. That's why I always re-generate them before issuing a new release to the Operatorhub.

**Comment by vmuzikar** [comment]
@slaskawi Thanks, that sounds like a good idea. :)

Maybe we could have some GH Action that would warn the contributor if it detects changes to the CRDs after running `make code/gen`.

**Comment by slaskawi** [comment]
Sounds like a plan!

**Comment by vmuzikar** [comment]
@slaskawi I think we're good to go. Could you please merge?

**Comment by kfox1111** [comment]
Would it make sense to make a catalog / bundle for keycloak-operator so that syncing is no longer required?

**Comment by slaskawi** [comment]
@kfox1111 This idea circulates back from time to time. But there are some projects that actually depend on our structure here. I'll talk with them if we could break this dependency somehow.

**Review by slaskawi — APPROVED** [review]

**Comment by slaskawi** [comment]
Integrated, thanks @vmuzikar

**Pull request merged**
