### PR TITLE
fix an few issues discovered when test monitoring

### PR DESCRIPTION
**Pull request by wei-lee**
## JIRA ID
https://issues.redhat.com/browse/INTLY-5027

## Verification Steps

Check the alerts here: https://prometheus-route-rhmi-middleware-monitoring.apps.weili-43.w3g9.s1.devshift.org/alerts. You should see alerts for 2 instances of keycloak are working

## Checklist:
- [ ] Verified by team member
- [ ] Comments where necessary
- [ ] Automated Tests
- [ ] Documentation changes if necessary

### CODE REVIEW

**Comment by stianst** [comment]
We need a Keycloak JIRA for this one, and the commit message should be pre-fixed with the Keycloak JIRA issue.

**Comment by wei-lee** [comment]
@stianst @davidffrench commits squashed and prefixed with the Keycloak JIRA.

**Comment by stianst** [comment]
Rebase needed I'm afraid :/

**Comment by wei-lee** [comment]
@slaskawi done!

**Comment by davidffrench** [comment]
@stianst This is ready to be merged when you are ready.

**Comment by slaskawi** [comment]
@stianst @abstractj This one is ready to be merged.

**Pull request merged**
