### PR TITLE
KEYCLOAK-12623 8.0.1 OLM descriptor

### PR DESCRIPTION
**Pull request by slaskawi**
## JIRA ID

[KEYCLOAK-12623](https://issues.redhat.com/browse/KEYCLOAK-12623)

## Additional Information

This Pull Request synchronizes OLM information with:

* https://github.com/operator-framework/community-operators/pull/1087
* https://github.com/operator-framework/community-operators/pull/1088

## Checklist:
- [ ] Verified by team member
- [ ] Comments where necessary
- [ ] Automated Tests
- [ ] Documentation changes if necessary

### CODE REVIEW

**Comment by kfox1111** [comment]
This is important to get merged, considering the security issue. Getting the fix in https://github.com/keycloak/keycloak-operator/pull/115 is also important though, as I can't seem to get things to work without it.

**Comment by slaskawi** [comment]
@kfox1111 Thanks for the comment.

Just FYI - this is just sync commit (for the reference). There are two Pull Requests against the Operatorhub that are more important than this one. 

If you urgently need `8.0.1` release, please use the code directly from the tag: https://github.com/keycloak/keycloak-operator/releases/tag/8.0.1

**Comment by kfox1111** [comment]
Ah, ok. Thanks for the info.

**Comment by slaskawi** [comment]
@abstractj This one can be merged (as Operatorhub PR have just been merged)

**Pull request merged**
