### PR TITLE
Added WebAuthn fields to the CRD

### LINKED ISSUE #539: Add WebAuthn fields to the CRD
### Description

The operator supports configuring the realm, but the KeycloakRealm resource is missing the WebAuthn fields from the [RealmRepresentation](https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_realmrepresentation) model, so you can't configure Keycloak to use them.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by stustison**
## Related GH Issue
Closes #539 

## Additional Information
Adds WebAuthn fields to the CRD

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@stustison Thank you for your contribution! Changes LGTM. Could you please rebase to resolve conflicts?

**Comment by stustison** [comment]
@vmuzikar it should be fixed now, thanks!

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@stustison Thanks for the update! I noticed there are some test and linter errors. Could you please check it out when you have a chance?

**Comment by stustison** [comment]
@vmuzikar everything is passing now, sorry about the long delay

**Comment by stustison** [comment]
@vmuzikar This should be ready to go. Let me know if there is something else needed. Thanks!

**Comment by vmuzikar** [comment]
@stustison Thank you for you contribution. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. However, since it adds functionality to the Realm CR, it is still relevant for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator). Since this PR requires a rebase, please consider opening this PR again there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!

**Pull request closed without merging**
