### PR TITLE
KEYCLOAK-16766 Bump backup-container image to latest 1.0.16

### PR DESCRIPTION
**Pull request by grdryn**
## JIRA ID

https://issues.redhat.com/browse/KEYCLOAK-16766

## Additional Information

A new version of the backup-container image has been published. There are no changes that affect the Keycloak operator's usage of it, so this is mostly just a respin on top of an updated base image.

https://quay.io/repository/integreatly/backup-container?tab=tags

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by grdryn** [comment]
@slaskawi @pb82 FYI :slightly_smiling_face:

**Comment by slaskawi** [comment]
@miquelsi May I ask you to review this one?

@grdryn One thing - could you please change the commit message and include a Keycloak JIRA?

**Comment by grdryn** [comment]
> could you please change the commit message and include a Keycloak JIRA?

I've updated that now, thanks! :+1:

**Review by miquelsi — APPROVED** [review]

**Review by slaskawi — APPROVED** [review]

**Comment by slaskawi** [comment]
Integrated, thanks @grdryn and @miquelsi !

**Pull request merged**
