### PR TITLE
KEYCLOAK-12273 Keycloak Operator documentation

### PR DESCRIPTION
**Pull request by slaskawi**
## JIRA ID

[KEYCLOAK-12273](https://issues.redhat.com/browse/KEYCLOAK-12273)
## Checklist:
- [ ] Verified by team member
- [ ] Comments where necessary
- [ ] Automated Tests
- [ ] Documentation changes if necessary

### CODE REVIEW

**Comment by slaskawi** [comment]
Please merge this one after https://github.com/keycloak/keycloak-documentation/pull/796

**Comment by abstractj** [comment]
Just added a label to prevent accidental merge, until we get https://github.com/keycloak/keycloak-documentation/pull/796 merged.

**Comment by abstractj** [comment]
@stianst @slaskawi shall we keep this on hold?

**Comment by slaskawi** [comment]
@abstractj Yes, that's a good point. Currently the documentation is not yet visible (although it has already been pushed to `master`). Let's wait till 11 is out.

**Comment by slaskawi** [comment]
I rebased this one. Ready to be reviewed @vmuzikar @ASzc @abstractj

**Comment by slaskawi** [comment]
> Just an idea of enhancement, do you think you would be able to add steps on how to debug e2e tests from Goland/vscode? I was able to do it in Goland, but I lost it, unfortunately. I remember I needed to put some of the arguments from here: https://github.com/keycloak/keycloak-operator/blob/master/Makefile#L60 to program arguments and some to Go tool arguments. I can try to investigate it more if you want.

@mhajas I would be very interested in this myself. I haven't done this before and I've been using logging to debug e2e tests. I hope you'll find your notes and share it :) It would be great to plug the debugger in during the tests :)

**Comment by slaskawi** [comment]
@mhajas @vmuzikar @abstractj Added an information how to debug e2e tests from @mhajas (good stuff!).

**Comment by slaskawi** [comment]
@abstractj Could you please review it and merge it?

**Comment by abstractj** [comment]
@slaskawi LGTM

**Pull request merged**
