### PR TITLE
[KEYCLOAK-16365] Remove any references to Travis in the Operator repository

### PR DESCRIPTION
**Pull request by abstractj**
Follow up task for https://issues.redhat.com/browse/KEYCLOAK-16142

### CODE REVIEW

**Review by vmuzikar — APPROVED** [review]

**Review by miquelsi — DISMISSED** [review]

**Review by slaskawi — APPROVED** [review]
LGTM but let's wait till https://github.com/keycloak/keycloak-operator/pull/271 gets in.

**Comment by slaskawi** [comment]
@abstractj Would you mind to rebase it?

**Comment by slaskawi** [comment]
@abstractj Could you please rebase it?

**Comment by slaskawi** [comment]
@abstractj Could you please rebase it?

**Comment by slaskawi** [comment]
@abstractj Any update?

**Comment by slaskawi** [comment]
@abstractj I tried to rebase and fix the conflicts using Github UI but it seems I failed to do so. Please rebase it yourself and let me know.

**Comment by slaskawi** [comment]
Closing because of lack of activity. Please reopen when ready.

**Pull request closed without merging**
