### PR TITLE
KEYCLOAK-19667 Add s390x support to keycloak-operator docker image

### PR DESCRIPTION
**Pull request by kun-lu20**
## JIRA ID

https://issues.redhat.com/browse/KEYCLOAK-19667

## Additional Information

This PR is to add s390x (multi-arch) support on GitHub Actions workflow to build and release keycloak-operator docker images.

## Checklist:
- [x] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by kun-lu20** [comment]
Hi @vmuzikar , could you please review this PR when you have some time? Thank you!

**Comment by kun-lu20** [comment]
Hi @jonathanvila , could you please review this PR when you're available? Thanks!

**Comment by kun-lu20** [comment]
Hi @vmuzikar , hope all is well with you.

Looks like the release of Keycloak 17 is postponed. Can we go ahead with this PR to add s390x support to Keycloak-operator image first? Thank you very much!

**Comment by vmuzikar** [comment]
@kun-lu20 Per our discussion offline, s390x support will be added later and only for [the new operator](https://github.com/keycloak/keycloak/tree/main/operator). Hence closing this.

**Pull request closed without merging**
