### PR TITLE
[DO NOT MERGE] Update the operator-sdk version from v0.10.0 to v0.11.0

### PR DESCRIPTION
**Pull request by davidffrench**
## JIRA ID
https://issues.jboss.org/browse/INTLY-3929

## Additional Information
Update the operator-sdk version to v0.11.0 following this guide - https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v011x

The newest version includes the controller-runtime version v0.2.0 which includes webhook refactor.

## Verification Steps
1. Run the operator on a cluster
2. Create a Keycloak and KeycloakRealm CR
3. Verify everything is working as expected

## Checklist:
- [ ] Verified by team member
- [ ] Comments where necessary
- [ ] Automated Tests
- [ ] Documentation changes if necessary

### CODE REVIEW

**Comment by slaskawi** [comment]
@davidffrench Please fix Travis build. Apart from that, LGTM.

**Comment by davidffrench** [comment]
Realised with this PR that https://github.com/keycloak/keycloak-operator/pull/55/files gets reverted everytime we run the file generation. This is unavoidable until there is a kubebuilder marker from what I can see. https://github.com/kubernetes-sigs/controller-tools/issues/281

**Comment by davidffrench** [comment]
Looks like the latest version is not compatible with Kubernetes 1.11.x. Waiting on an answer from https://github.com/operator-framework/operator-sdk/issues/2118

**Comment by davidffrench** [comment]
The Travis failure is another reason not to merge this.
```
verifying github.com/operator-framework/operator-sdk@v0.11.0: checksum mismatch
	downloaded: h1:tQumPT2UjD6uhggfAerRbPt+rWOPKC80DmgKUEqeGYo=
	go.sum:     h1:If0MefBJjPGYAW6Os6azpTMoaFtsSlXRlQctF23/ORs=
```
Unsure why this is happening but some research seems to indicate it is due to using Go 1.13, unsure why that would be though.

**Comment by abstractj** [comment]
> The Travis failure is another reason not to merge this.
> 
> ```
> verifying github.com/operator-framework/operator-sdk@v0.11.0: checksum mismatch
> 	downloaded: h1:tQumPT2UjD6uhggfAerRbPt+rWOPKC80DmgKUEqeGYo=
> 	go.sum:     h1:If0MefBJjPGYAW6Os6azpTMoaFtsSlXRlQctF23/ORs=
> ```
> 
> Unsure why this is happening but some research seems to indicate it is due to using Go 1.13, unsure why that would be though.

@davidffrench have you tried `go mod tidy`?

**Comment by davidffrench** [comment]
> > The Travis failure is another reason not to merge this.
> > ```
> > verifying github.com/operator-framework/operator-sdk@v0.11.0: checksum mismatch
> > 	downloaded: h1:tQumPT2UjD6uhggfAerRbPt+rWOPKC80DmgKUEqeGYo=
> > 	go.sum:     h1:If0MefBJjPGYAW6Os6azpTMoaFtsSlXRlQctF23/ORs=
> > ```
> > 
> > 
> > Unsure why this is happening but some research seems to indicate it is due to using Go 1.13, unsure why that would be though.
> 
> @davidffrench have you tried `go mod tidy`?

I have, still happens. Even removing the `go.sum` and `vendor` folder, when you then run `go mod tidy`, it happens on that command

**Comment by slaskawi** [comment]
Let me close this for now. @davidffrench Please reopen it once you have a clarification if we need this or not.

**Pull request closed without merging**
