### PR TITLE
#508 Add identityProviderMappers to KeycloakRealm CR

### LINKED ISSUE #508: Support identityProviderMappers on Realm CR
### Description

The Realm CR supports the identityProvider field but not the identityProviderMappers field.

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by Robbilie**
## Related GH Issue
Closes #508

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Robbilie Thank you for your contribution! Changes LGTM, but we need a test for it. Could you please add some? You can extend [`keycloakRealmWithIdentityProviderTest`](https://github.com/keycloak/keycloak-operator/blob/d3a23151d79d9dce64178de80804e8347074bb02/test/e2e/keycloak_realm_test.go#L111).

**Comment by zonybob** [comment]
I am very interested in this change, and I can work to add the needed test(s). Would you prefer I create my own fork from `main` and copy in the changes that @Robbilie has already provided?

**Comment by zonybob** [comment]
> @zonybob @Robbilie Any of you guys working on the tests? Would be nice to have this feature.

I really would like to work on these... I have two concerns about my path forward that have kept me from touching it...
1. I know this project corresponds to the legacy/deprecated operator. Is there a path to make sure this feature is available in the new one as well?
2. We use the OpenShift SSO operator, and given the legacy deprecation, I don't even know if fixing this here will ever make its way to an OpenShift SSO release?

**Comment by abebehailu** [comment]
> > @zonybob @Robbilie Any of you guys working on the tests? Would be nice to have this feature.
> 
> I really would like to work on these... I have two concerns about my path forward that have kept me from touching it...
> 
> 1. I know this project corresponds to the legacy/deprecated operator. Is there a path to make sure this feature is available in the new one as well?
> 2. We use the OpenShift SSO operator, and given the legacy deprecation, I don't even know if fixing this here will ever make its way to an OpenShift SSO release?

I think the new Operator will have the feature, at least from the looks of their [example CRD](https://github.com/keycloak/keycloak/blob/main/operator/src/main/resources/example-realm.yaml#L1206). The documentation of the [Import CRD](https://www.keycloak.org/operator/realm-import) also specifies *This CR should be created in the same namespace as the Keycloak Deployment CR, defined in the field keycloakCRName. The realm field accepts a full RealmRepresentation*.

Regarding the OpenShift SSO, are refering to RH-SSO?

**Comment by zonybob** [comment]
> > > @zonybob @Robbilie Any of you guys working on the tests? Would be nice to have this feature.
> > 
> > 
> > I really would like to work on these... I have two concerns about my path forward that have kept me from touching it...
> > 
> > 1. I know this project corresponds to the legacy/deprecated operator. Is there a path to make sure this feature is available in the new one as well?
> > 2. We use the OpenShift SSO operator, and given the legacy deprecation, I don't even know if fixing this here will ever make its way to an OpenShift SSO release?
> 
> I think the new Operator will have the feature, at least from the looks of their [example CRD](https://github.com/keycloak/keycloak/blob/main/operator/src/main/resources/example-realm.yaml#L1206). The documentation of the [Import CRD](https://www.keycloak.org/operator/realm-import) also specifies _This CR should be created in the same namespace as the Keycloak Deployment CR, defined in the field keycloakCRName. The realm field accepts a full RealmRepresentation_.
> 
> Regarding the OpenShift SSO, are refering to RH-SSO?

Ok thanks... and yes, sorry, I meant RH SSO

**Review by vmuzikar — APPROVED** [review]
@Robbilie Thank you again for you contribution. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. However, since it adds functionality to the Realm CR, it is still relevant for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator). I will port this changes there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!

**Comment by vmuzikar** [comment]
This is being ported to the Realm Operator here: https://github.com/keycloak/keycloak-realm-operator/pull/4

**Pull request merged**
