### PR TITLE
KEYCLOAK-15446 Adding kustomize

### PR DESCRIPTION
**Pull request by Kampe**
## JIRA ID

https://issues.redhat.com/browse/KEYCLOAK-15446

## Checklist:
- [x] Automated Tests
- [x] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [x] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by slaskawi** [comment]
@Kampe Thanks for the Pull Request.

I'm putting this on hold and created a initiated a discussion on Keycloak DEV: https://groups.google.com/g/keycloak-dev/c/QS0i9UmvHJE

**Comment by slaskawi** [comment]
As mentioned on the Keycloak DEV, Kustomize will be part of Operator SDK scaffolded projects starting from 1.0.0.

I'm not an expert here, so I can't validate the content (@Kampe perhaps you could ask some of your colleagues to have a look at it). The file structure seems fine. I would only like you to create a JIRA for it and add it to the commit message.

**Comment by slaskawi** [comment]
Perhaps @pierreozoux and @mhutter would be interested in reviewing this. 

Just a quick recap for you - Operator SDK 1.0.0 is going to introduce kustomize for managing yaml files. Having this in mind, this PR has a green light. I know you were previously interested in this. Please see Keycloak DEV mailing list for more details.

**Comment by mhutter** [comment]
LGTM!

`<nitpick>`The root `kustomize.yaml` does not have a newline at the end of the file.`</nitpick>` :)

**Review by slaskawi — CHANGES_REQUESTED** [review]
The code itself looks good. But in order to integrate this we'll need:
- A JIRA
- all commits to be squashed and the commit message needs to be prefixed with JIRA ID. 

Once this is done, please ping me and I'll merge it.

**Review by slaskawi — APPROVED** [review]

**Comment by slaskawi** [comment]
Integrated, thanks @Kampe !

**Pull request merged**
