### PR TITLE
KEYCLOAK-15516 Update the image to UBI 8.2

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.redhat.com/browse/KEYCLOAK-15516

See https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.2&container-tabs=gti&gti-tabs=unauthenticated

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Review by miquelsi — DISMISSED** [review]

**Review by ASzc — CHANGES_REQUESTED** [review]
`productize.sh`, line 19, needs to be updated as well

**Comment by slaskawi** [comment]
> productize.sh, line 19, needs to be updated as well

@ASzc Actually, it needs to be removed. I've just updated it.

**Review by vmuzikar — APPROVED** [review]
As far as I can tell looks good. Thanks @slaskawi!

**Comment by slaskawi** [comment]
@abstractj May I ask you to merge this one?

**Comment by slaskawi** [comment]
@hmlnarik I rebased my PR. May I ask you again for the green stamp?

**Review by hmlnarik — APPROVED** [review]

**Pull request merged**
