### PR TITLE
KEYCLOAK-16906 changed fieldname authenticatorFlow to Keycloak fieldname

### PR DESCRIPTION
**Pull request by christianwoehrle**
## KEYCLOAK-16906
https://issues.redhat.com/browse/KEYCLOAK-16906

## Additional Information
If I create a KeycloakRealm with an AuthenticationFlow that contains an AuthenticationExecution with authenticatorFlow=true, then the realm is not created and keycloak logs a NullPointer Exception.

 
```

   authenticationFlows:
    - alias: "sub-flow"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []
    - alias: "main-flow"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions:
      - requirement: "ALTERNATIVE"
        priority: 10
        userSetupAllowed: false
        authenticatorFlow: true
        flowAlias: "sub-flow"
 
```

The reason for this is that the Keycloak Api expects a field autheticatorFlow but the KeycloakOperator sends a field authenticatorFlow.

See [KeycloakApi](https://www.keycloak.org/docs-api/12.0/rest-api/index.html#_authenticationexecutionrepresentation)

 

This is the line that causes the problem:
https://github.com/keycloak/keycloak-operator/blob/master/pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go#L231

 
The field name is changed to the name that is expected from Keycloak, i.e. autheticatorFlow

## Verification Steps

To reproduce the error create the keycloak and realm custom resource. This produces a null pointer exception in the keycloak logs and the realm is not created.

```

apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  namespace: keycloak
  labels:
    app: sso
spec:
  instances: 1
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: True
  podDisruptionBudget:
    enabled: True
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: test
  namespace: keycloak
  labels:
    app: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Realm
    enabled: true
    id: testrealm
    realm: testrealm
    authenticatorConfig:
      - alias: "oidc"
        config:
          defaultProvider: "oidc"
    authenticationFlows:
    - alias: "Main-Flow"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: 
      - requirement: "ALTERNATIVE"
        priority: 10
        userSetupAllowed: false
        authenticatorFlow: true
        flowAlias: "Sub-Flow"
    - alias: "Sub-Flow"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []

    - alias: "browser"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions:
      - authenticator: "identity-provider-redirector"
        authenticatorConfig: oidc
        requirement: "ALTERNATIVE"
        priority: 0
        userSetupAllowed: false
        authenticatorFlow: false
    - alias: "registration"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []
    - alias: "direct grant"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []

```

To check the Fix recreate the CRD for KeycloakRealm. Create the keycloak and realm custom resources below. This creates the realm with an AuthenticationFlow 

```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  namespace: keycloak
  labels:
    app: sso
spec:
  instances: 1
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: True
  podDisruptionBudget:
    enabled: True
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: test
  namespace: keycloak2
  labels:
    app: sso
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Realm
    enabled: true
    id: testrealm
    realm: testrealm
    authenticatorConfig:
      - alias: "oidc"
        config:
          defaultProvider: "oidc"
    authenticationFlows:
    - alias: "Main-Flow"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: 
      - requirement: "ALTERNATIVE"
        priority: 10
        userSetupAllowed: false
        autheticatorFlow: true
        flowAlias: "Sub-Flow"
    - alias: "Sub-Flow"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []

    - alias: "browser"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions:
      - authenticator: "identity-provider-redirector"
        authenticatorConfig: oidc
        requirement: "ALTERNATIVE"
        priority: 0
        userSetupAllowed: false
        autheticatorFlow: false
    - alias: "registration"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []
    - alias: "direct grant"
      providerId: "basic-flow"
      topLevel: true
      builtIn: false
      authenticationExecutions: []

```

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by abstractj** [comment]
@christianwoehrle thanks for submitting these changes, but I believe that's a typo and should be fixed in the Keycloak server.

I've submitted a PR for that https://github.com/keycloak/keycloak/pull/7739

Not sure what @slaskawi thinks.

**Comment by christianwoehrle** [comment]
@abstractj yes, that's a typo. 
I have seen that this typo is in the API since version 5.0 (https://www.keycloak.org/docs-api/5.0/rest-api/index.html)
and used in tools like the terraform provider of keycloak, so my feeling was this would be difficult to change in the server as it would break many clients.
This would have an impact on the keycloak-operator too, if the operator would have to support the old and new format, depending on the keycloak version.

**Comment by abstractj** [comment]
> @abstractj yes, that's a typo.
> I have seen that this typo is in the API since version 5.0 (https://www.keycloak.org/docs-api/5.0/rest-api/index.html)
> and used in tools like the terraform provider of keycloak, so my feeling was this would be difficult to change in the server as it would break many clients.
> This would have an impact on the keycloak-operator too, if the operator would have to support the old and new format, depending on the keycloak version.

You are correct on your assumption, but I'm afraid that if we don't fix the typo will be replicated to future clients, or new applications willing to integrate with Keycloak.

**Comment by christianwoehrle** [comment]
I did some more testing.

The error occurs when keycloak-operator uses the keycloak image  quay.io/keycloak/keycloak:9.0.2.
The error also occurs when I set the environment variable RELATED_IMAGE_KEYCLOAK in the keycloak-operator to the newest keycloak image quay.io/keycloak./keycloak:12.0.2.

The keycloak-operator POSTs the real-configuration to https://localhost:8443/auth/admin/realms/

When I try the post with POSTMAN I get the error 
`Unrecognized field "authenticatorFlow" (class org.keycloak.representations.idm.AuthenticationExecutionExportRepresentation), not marked as ignorable`

I works in POSTMAN as soon as I replace the field authenticatorFlow with autheticatorFlow.

In Keycloak the class org.keycloak.representations.idm.AuthenticationExecutionExportRepresentation extends AbstractAuthenticationExecutionRepresentation

and here the interface is still with the typo (since 2016) although the internal representation is ok.

    public boolean isAutheticatorFlow() {
        return authenticatorFlow;
    }
    public void setAutheticatorFlow(boolean autheticatorFlow) {
        this.authenticatorFlow = autheticatorFlow;
    }


When I export the realm definition (e.g. for the default master realm) via the keycloak web-application, I also get the field autheticatorFlow. 

If this cannot be changed in keycloak in the foreseeable future, would it be possible to merge this fix to get this functionality working?

**Comment by slaskawi** [comment]
In general I would prefer not to fix it here but rather in the Keycloak Server. So I agree with @abstractj here.

On the other hand, @abstractj's PR changes the representation, which also changes our contract with the users. Having this in mind, we should only change this in the next major. 

@abstractj Do you have any ETA when your change gets into the server?

**Comment by slaskawi** [comment]
@abstractj Could you please take a look at my previous comment?

**Comment by abstractj** [comment]
@slaskawi we need to consider Marek's comments here https://github.com/keycloak/keycloak/pull/7739. Even though I appreciate the contribution to this PR, I believe we should close it, as the proper fix should happen in the Keycloak codebase.

If you would you or the author of this PR would like to take over my PR, there’s no problem.

**Comment by christianwoehrle** [comment]
@slaskawi sorry, I wouldn´t know how to fix that in keycloak itself. 

I agree that it would be a nicer solution if it was fixed in keycloak. 
But the fact that the typo is there since at least release 5 seems to indicate that it is difficult to fix and might not be fixed soon.

If we don't get a fix there, would it be an option to use this PR. It would solve the current problem, there wouldn't be any conflicts between versions. 
What do you think?

**Comment by slaskawi** [comment]
@chlunde Sorry to disappoint you, but the way to move this forward is to get https://github.com/keycloak/keycloak/pull/7739 in. Closing this.

**Comment by christianwoehrle** [comment]
@slaskawi  I was fine with a fix via https://github.com/keycloak/keycloak/pull/7739 but this issue has been closed now. 

We currently use a patched version of the keycloak operator to provision our AuthenticationFlows. 

If you would consider solving the typo on the client side then I'd update my merge request. Please let me know.

**Comment by pskopek** [comment]
@christianwoehrle here is new PR to fix the typo issue in Keycloak. https://github.com/keycloak/keycloak/pull/8001
Can you check if it works for you, please? (Use JIRA in the PR for comments)

**Pull request closed without merging**
