### PR TITLE
Mark MultiNamespace as supported

### PR DESCRIPTION
**Pull request by sathieu**
## Additional Information

it's supported in the code:

https://github.com/keycloak/keycloak-operator/blob/996c21bca9f1d948e784d4f1ef5caaba5088944e/cmd/manager/main.go#L117-L124

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by Robbilie** [comment]
I contributed a fix to make everything multi namespace compatible since i am running it multi namespace but they rejected it:

https://github.com/keycloak/keycloak-operator/pull/363

**Comment by sathieu** [comment]
@Robbilie Thanks for the info. That's sad. I hope they'll change their mind ...

**Comment by Robbilie** [comment]
i agree, especially because my code change only expands the feature set and allows for gitops usecases to work more smoothly :)

**Comment by sathieu** [comment]
@vmuzikar How should this operator be used if it can't watch other namespaces (and create secrets in other NS) ?

**Comment by sathieu** [comment]
Thanks @vmuzikar. I'm looking forward for keycloak.X!

In the meantime, I'll use kubed to copy secrets between the keycloak namespace and the destination namespace.

**Pull request closed without merging**
