### PR TITLE
Add flow bindings to KeycloakRealm resource

### LINKED ISSUE #528: Add flow bindings to KeycloakRealm resource
### Description

The operator supports adding custom authentication flows, but the KeycloakRealm resource lacks the flow binding fields from the [RealmRepresentation](https://www.keycloak.org/docs-api/17.0/rest-api/index.html#_realmrepresentation) model, so you can't configure Keycloak to use them.

These fields should be added to allow modifying the authentication flow bindings

### Discussion

_No response_

### Motivation

There's no way to modify authentication flow bindings for a realm currently

### Details

_No response_

### PR DESCRIPTION
**Pull request by SmithJosh**
## Related GH Issue
Closes https://github.com/keycloak/keycloak-operator/issues/528

## Verification Steps

1. Run the operator
2. Create a realm resource with custom authentication flows and which enables these flows using the new flow binding fields 
3. Check that the requested bindings are reflected in Keycloak

## Checklist:
- [x] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@SmithJosh Thank you for your contribution! Changes LGTM. Can you also please add the `dockerAuthenticationFlow` to fully match the [RealmRepresentation](https://github.com/keycloak/keycloak/blob/ac79fd0c23c6947a04073afc61e30d341498438e/core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java#L201)?

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@SmithJosh One last thing. Could you please rebase?

**Comment by vmuzikar** [comment]
Thanks for the update!

Something weird was going on with the GH Actions. Closed and re-opened the PR to fix it.

**Comment by SmithJosh** [comment]
Thanks @vmuzikar! I'll see if I can get that test failure fixed

**Comment by SmithJosh** [comment]
@vmuzikar I tried to fix the test, but I'm struggling to run `make test/e2e` locally, and the output from the CI Tests check isn't very helpful. Do you have any ideas?

**Comment by stustison** [comment]
@vmuzikar This PR should be ready to go now as well.

**Review by vmuzikar — APPROVED** [review]
@SmithJosh Thank you again for you contribution. Keycloak 19 was the last version that included this legacy Operator, and with the release of Keycloak 20 the Operator reached EOL, please see our [blog post](https://www.keycloak.org/2022/03/releases.html) on this topic. However, since it adds functionality to the Realm CR, it is still relevant for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator). I will port this changes there. Thanks for your understanding. And be sure to check out our [new Operator](https://www.keycloak.org/guides#operator)!

**Comment by vmuzikar** [comment]
This is being ported to the Realm Operator here: https://github.com/keycloak/keycloak-realm-operator/pull/4

**Pull request merged**
