### PR TITLE
KEYCLOAK-14888 Create container build workflow for Quay

### PR DESCRIPTION
**Pull request by ASzc**
When:

- a commit is pushed to any branch,
- or when a commit is tagged

build the Dockerfile located in the repo root, then push it to
https://quay.io/repository/keycloak/keycloak-operator

### CODE REVIEW

**Comment by ASzc** [comment]
Expanded it a bit, to also check pull requests. When it's a pull request it won't push to Quay.

**Comment by abstractj** [comment]
@ASzc did you get the chance to test it using your fork and your quay account?

**Comment by ASzc** [comment]
@abstractj It did run on my fork, [here](https://github.com/ASzc/keycloak-operator/runs/916235380?check_suite_focus=true). However, because I don't have the credentials there, it fails with an auth error when trying to push the image.

**Comment by ASzc** [comment]
I will sign up for Quay and see if I can get it to push to somewhere else

**Comment by ASzc** [comment]
@abstractj Tested, and it works. See the successful run [here](https://github.com/ASzc/keycloak-operator/runs/924096315), and the quay output [here](https://quay.io/repository/aszc/keycloak-operator?tab=tags).

I made a [nifty custom Github action](https://github.com/marketplace/actions/change-string-case), that should make it so that we can just drop in this YAML into any of our repos without modification.

I had to both create a bot account, and also grant write permission to that bot account, in order for the push to work.

**Comment by abstractj** [comment]
@ASzc reviewing the logs here:

```
Successfully tagged quay.io/keycloak/keycloak-operator:KEYCLOAK-14888
Pushing image [quay.io/keycloak/keycloak-operator:KEYCLOAK-14888]
The push refers to repository [quay.io/keycloak/keycloak-operator]
75c839e32c02: Preparing
4a06f53ca5ae: Preparing
0c8105532ca3: Preparing
eddba477a8ae: Preparing
f80c95f61fff: Preparing
unauthorized: access to the requested resource is not authorized
Error: exit status 1
```
It returns `unauthorized`, but I believe that's because you don't have the access token to the Keycloak account on Quay.io. My suggestion is to point to your Quay account for testing purposes, so we can see the outcome.

While reading the logs and the summary I have one question. It seems to me that if we create a branch like `dev`. The image will be pushed and tagged as `dev`. If my assumption is correct, my suggestion is to push images only when:

- A new tag is created
- Changes are pushed to master

**Comment by ASzc** [comment]
Yes, I did that. It works without error now. See my links in the last comment.

```
Successfully built f2d84fbdcaf2
Successfully tagged quay.io/aszc/keycloak-operator:KEYCLOAK-14888
Pushing image [quay.io/aszc/keycloak-operator:KEYCLOAK-14888]
The push refers to repository [quay.io/aszc/keycloak-operator]
b6d711e20dbe: Preparing
d79c9920e4ed: Preparing
3a432137fa20: Preparing
eddba477a8ae: Preparing
f80c95f61fff: Preparing
f80c95f61fff: Layer already exists
eddba477a8ae: Layer already exists
d79c9920e4ed: Pushed
b6d711e20dbe: Pushed
3a432137fa20: Pushed
KEYCLOAK-14888: digest: sha256:8703c1cd78917c2d4dc8cfcefbcf905f89de60481a7f3b02648a6cbda3652fbc size: 1368
```

I'll make the change to restrict builds to master branch or tags.

**Comment by ASzc** [comment]
```diff
diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
index 6742f04..40cfd0a 100644
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -33,4 +33,4 @@ jobs:
           registry: quay.io
           tag_with_ref: true
           always_pull: true
-          push: ${{ ! startsWith(github.ref, 'refs/pull/') }}
+          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
```

**Comment by ASzc** [comment]
@abstractj Should be good to merge

**Comment by slaskawi** [comment]
Good stuff @ASzc !!!

Is it possible to create push images for all Pull Requests? This would be super convenient for reviewing PRs. What do you think?

**Pull request merged**
