### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by Kent1**

### CODE REVIEW

**Review by pgbezerra — APPROVED** [review]

**Review by vmuzikar — CHANGES_REQUESTED** [review]
@Kent1 Thank you for your contribution!
Could you please create a JIRA for your changes? Please see the [contribution guide](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md).

**Comment by Kent1** [comment]
https://issues.redhat.com/browse/KEYCLOAK-19040

**Comment by vmuzikar** [comment]
@pskopek @ASzc @drichtarik Could you please double check that we don't use  misspelled `GOACH` var anywhere in prod?

**Comment by drichtarik** [comment]
@vmuzikar I checked the operator prod repo and also the containers prod repo and only found the equivalent of this typo in the operator prod repo.

**Review by drichtarik — APPROVED** [review]

**Comment by drichtarik** [comment]
BTW this needs a better commit message to follow the rules of keycloak commit messages: https://issues.redhat.com/browse/KEYCLOAK-19040
Also needs to reflect the JIRA name

**Comment by vmuzikar** [comment]
@drichtarik Thanks for the review!
> BTW this needs a better commit message to follow the rules of keycloak commit messages: https://issues.redhat.com/browse/KEYCLOAK-19040
> Also needs to reflect the JIRA name
I believe the commit message is correct.

**Review by vmuzikar — APPROVED** [review]

**Pull request merged**
