### PR TITLE
[KEYCLOAK-16142] Replace Travis with Github Actions

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Review by slaskawi — CHANGES_REQUESTED** [review]
I love the changes @abstractj !

There are two things that I miss from this Pull Request:
1) A small documentation snippet explaining how to debug the Github pipeline locally. This might be helpful when investigating failures.
2) Removal of all the Travis bits (Travis file, Makefile Targets, Readme entries). 

Once both are done - please ping me and I'll merge it.

**Comment by abstractj** [comment]
> I love the changes @abstractj !
> 
> There are two things that I miss from this Pull Request:
> 
>     1. A small documentation snippet explaining how to debug the Github pipeline locally. This might be helpful when investigating failures.

Do you have any pointers for the similar documentation for Travis that you're asking?

> 
>     2. Removal of all the Travis bits (Travis file, Makefile Targets, Readme entries).

As discussed few days ago, the plan is to run both in parallel and once we have confidence that GH actions is working as expected, we remove Travis bits.

> 
> 
> Once both are done - please ping me and I'll merge it.

**Comment by slaskawi** [comment]
Travis has a nice manual entry about debugging the builds:
https://docs.travis-ci.com/user/running-build-in-debug-mode/

I believe (but I may be mistaken here) that Github Actions can be run
locally. Do you have any experience with this? If not - we can skip this
section for now.

**Comment by abstractj** [comment]
> Travis has a nice manual entry about debugging the builds: https://docs.travis-ci.com/user/running-build-in-debug-mode/ I believe (but I may be mistaken here) that Github Actions can be run locally. Do you have any experience with this? If not - we can skip this section for now.

The only thing close to what you mention to run it locally is [act](https://github.com/nektos/act). I tried it and gave up. The only way I know at the moment is pretty much making changes, pushing to GitHub, and running it to debug issues.

**Comment by slaskawi** [comment]
@abstractj Understood. Ok, than - let's merge this one.

**Review by slaskawi — APPROVED** [review]

**Comment by slaskawi** [comment]
Integrated, thanks @abstractj

**Pull request merged**
