### PR TITLE
Update constants.go

### PR DESCRIPTION
**Pull request by linkafsar**
## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by slaskawi** [comment]
@linkafsar Thanks for the Pull Request.

Unfortunately as it is now, this PR can not be accepted. The description doesn't contain any useful information and there's no JIRA assigned to it. Please have a look at our Contribution Guide: https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md

I'm closing it for now. Please reopen when ready for review.

**Comment by linkafsar** [comment]
Hi Sebastian, 


How can we create a postgresql 2 instances. 


Thanks 
Afsar Khan

**Comment by slaskawi** [comment]
@linkafsar Unfortunately there's no way to do it at the moment. If this is an important case for you, please create a JIRA with some brief explanation about your use case.

**Comment by linkafsar** [comment]
Hi Sebastian, 

Sure but i also need to configure postgresql in HA mode or we can say replica of postgresql 

Is it possible ? 

Thanks 
Afsar Khan

**Comment by slaskawi** [comment]
@linkafsar Yes, that possible. You need to host your database manually. Please read this paragraph of the documentation: https://github.com/keycloak/keycloak-documentation/blob/master/server_installation/topics/operator/external-database.adoc

**Pull request closed without merging**
