### PR TITLE
feat: enable pruning in the CRDs to prevent storing unknown fields in etcd

### PR DESCRIPTION
**Pull request by malmuzaini**
## Additional Information

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields

## Checklist:
- [ ] Verified by team member
- [ ] Comments where necessary
- [ ] Automated Tests
- [ ] Documentation changes if necessary

### CODE REVIEW

**Comment by davidffrench** [comment]
Thank you very much for your contribution @malmuzaini . Sorry for the slow response, most of the team is at an event this week. I wasn't aware of this feature and it looks good, no cons that I can see for including it.

@slaskawi Would you be able to look into why Travis is failing, this doesn't look to be because of the change in this PR.

**Comment by slaskawi** [comment]
@malmuzaini So it seems Travis wasn't able to create CRDs - here's an error message:

```
Error from server (Invalid): error when creating "deploy/crds/Keycloak.yaml": CustomResourceDefinition.apiextensions.k8s.io "keycloaks.keycloak.org" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root

Error from server (Invalid): error when creating "deploy/crds/KeycloakRealm.yaml": CustomResourceDefinition.apiextensions.k8s.io "keycloakrealms.keycloak.org" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
```

**Comment by malmuzaini** [comment]
@slaskawi Fixed. My apologies for that.

**Comment by slaskawi** [comment]
Looks great! Thanks @malmuzaini

**Pull request merged**
