### PR TITLE
update crds since apiextensions.k8s.io/v1beta1 got deprecated

### PR DESCRIPTION
**Pull request by d-baranowski**
## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by slaskawi** [comment]
Thanks for contributing this!

Let me put this on hold as we need to have some discussion on this within our team.

**Review by slaskawi — CHANGES_REQUESTED** [review]
We discussed this internally and we can move this forward. 

Before this gets in, we need a few changes:
- Please add a JIRA ID to the commit message.
- Please have a look at our Makefile and update the `code/gen` target.
- Please rebase your change and squash everything into one commit.

**Comment by d-baranowski** [comment]
@slaskawi Hi. I don't know where to get the JIRA ID from. Can you provide it for me?

**Comment by slaskawi** [comment]
@d-baranowski Yes! Our JIRA is here: https://issues.redhat.com/projects/KEYCLOAK

**Comment by slaskawi** [comment]
Any update @d-baranowski ?

**Comment by slaskawi** [comment]
Any update @d-baranowski ?

**Comment by slaskawi** [comment]
Closing due to lack of activity. Please reopen once ready to be reviewed.

**Pull request closed without merging**
