### PR TITLE
KEYCLOAK-17233 Allow mounting multiple secrets and configmaps to volumes

### PR DESCRIPTION
**Pull request by soleblaze**
## JIRA ID
https://issues.redhat.com/browse/KEYCLOAK-16003
https://issues.redhat.com/browse/KEYCLOAK-17233

## Additional Information
This is needed to mount keytabs stored as secrets. It's also needed to use the keycloak plaintext vault functionality that allows us to store ldap passwords in secrets.

## Verification Steps
Create a secret named keytab that contains a test key:value
Create a keycloak instance using the following, or something similiar (as seen in deploy/examples/keycloak/keycloak-with-experimental-settings.yaml):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  test.properties: |
    blah=true
---
apiVersion: v1
kind: Secret
metadata:
  name: keytabs
data:
  krb5.keytab: RkFLRSBLRVlUQUIK
---
apiVersion: v1
kind: Secret
metadata:
  name: realm1-keytab
data:
  realm1.keytab: RkFLRSBLRVlUQUIK
---
apiVersion: v1
kind: Secret
metadata:
  name: realm2-keytab
data:
  realm2.keytab: RkFLRSBLRVlUQUIK
---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: True
  keycloakDeploymentSpec:
    experimental:
      args:
        - "-Djboss.as.management.blocking.timeout=600"
      env:
        - name: PROXY_ADDRESS_FORWARDING
          value: "false"
      volumes:
        defaultMode: 0777
        items:
          - name: keytab
            mountPath: /keytabs
            secrets:
              - keytab
          - name: vault
            mountPath: /opt/jboss/keycloak/secrets
            secrets:
              - realm1
              - realm2
          - name: test-config
            mountPath: /configmap
            configMaps:
              - test-config
```
Validate that keycloak-0 came up properly and mounted the keytabs secret to the /keytabs path and the realm secrets are mounted to /opt/jboss/keycloak/secrets

## Checklist:
- [X] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [X] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

### CODE REVIEW

**Comment by soleblaze** [comment]
Looks like the CI failed due to the minikube environment the e2e runs in not getting setup properly at the start. Can someone kick it to see if it's a fluke?

**Comment by kfox1111** [comment]
Not sure anyone else is watching. :(
Maybe ping someone on the ticket?

**Comment by slaskawi** [comment]
Hey @soleblaze and @kfox1111 

Looking into this PR is on list but unfortunately I'm working on some high priority items that consumes most of my time. I plan to look into this till the end of this week. Thanks for patience!

**Comment by kfox1111** [comment]
@slaskawi ok, no worries. just wanted to make sure it didn't get dropped by accident. Thanks! :)

**Comment by slaskawi** [comment]
Recently we applied a fix for our CI. Could you please rebase your Pull Request?

**Review by slaskawi — COMMENTED** [review]
The proposed change looks good to me! I believe we need a rebase and we should be good.

**Comment by soleblaze** [comment]
Looks like registry.svc.ci.openshift.org is currently down, breaking the build. Also, when I ran code/gen it replaced all the github.com/keycloak-operator references (like github.com/keycloak-operator/pkg/apis/keycloak/v1alpha1.Keycloak) with . (./pkg/apis/keycloak/v1alpha1.Keycloak). Is this expected or is there something else I need to set when I run code/gen?

**Comment by slaskawi** [comment]
Sorry for that - it seems the image pull spec has change. Would you mind to rebase again @soleblaze ?

**Review by slaskawi — DISMISSED** [review]

**Comment by slaskawi** [comment]
@soleblaze The code itself looks good to me. Could you please resolve all the conflicts and squash your commits into 1?

**Comment by soleblaze** [comment]
@slaskawi Ok, it's squashed down to a single commit. Let me know if you need anything else.

**Review by slaskawi — APPROVED** [review]

**Comment by slaskawi** [comment]
Integrated, thanks!

**Pull request merged**
